config/routes.rb
Listr::Application.routes.draw do
  get "welcome/index"

   resources :films

  root to: "welcome#index"

end

app/models/film.rb
class Film < ActiveRecord::Base
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
	
	def new
		@film = Film.new
	end

	def create
		@film = Film.new(params[:film].permit(:title))

		if @film.save
			redirect_to @film
		else
			render 'new'
		end
	end

	def show
	  @film = Film.find(params[:id])
	end

	def index
	  @films = Film.all
	end

	private
		def film_params
			params.require(:film).permit(:title)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/films/index.html.erb
<h1>All My Films</h1>
 
<table>
  <tr>
    <th>Title</th>
  </tr>
 
  <% @films.each do |film| %>
    <tr>
      <td><%= film.title %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'New film', new_film_path %>
</p>

app/views/films/new.html.erb
<h1>New Film</h1>
<%= form_for :film, url: films_path do |f| %>

	<% if @film.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@film.errors.count, "error") %> prohibited
	      this film from being saved:</h2>
	    <ul>
	    <% @film.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @film.title %>
</p>
<p>
	<%= link_to 'Back', films_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Listr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Listr</h1>
<p>Listr is a way for us to keep track of the things we have and the things we want</p>

<%= link_to "My Films", controller: "films" %>